from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('employees/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employees/add/', views.EmployeeCreateView.as_view(), name='employee_add'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employees/<int:pk>/edit/', views.EmployeeUpdateView.as_view(), name='employee_edit'),
    path('departments/', views.DepartmentListView.as_view(), name='department_list'),
    path('departments/add/', views.DepartmentCreateView.as_view(), name='department_add'),
    path('departments/<int:pk>/edit/', views.DepartmentUpdateView.as_view(), name='department_edit'),
    path('schedules/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/add/', views.ScheduleCreateView.as_view(), name='schedule_add'),
    path('schedules/<int:pk>/edit/', views.ScheduleUpdateView.as_view(), name='schedule_edit'),
    path('shifts/', views.ShiftListView.as_view(), name='shift_list'),
    path('shifts/add/', views.ShiftCreateView.as_view(), name='shift_add'),
    path('shifts/<int:pk>/edit/', views.ShiftUpdateView.as_view(), name='shift_edit'),
    path('attendance/', views.AttendanceRecordListView.as_view(), name='attendance_records'),
    path('leave/', views.LeaveListView.as_view(), name='leave_list'),
    path('leave/add/', views.LeaveCreateView.as_view(), name='leave_add'),
    path('leave/<int:pk>/edit/', views.LeaveUpdateView.as_view(), name='leave_edit'),
    path('holidays/', views.HolidayListView.as_view(), name='holiday_list'),
    path('holidays/add/', views.HolidayCreateView.as_view(), name='holiday_add'),
    path('holidays/<int:pk>/edit/', views.HolidayUpdateView.as_view(), name='holiday_edit'),
    path('reports/', views.ReportsView.as_view(), name='reports'),
    path('notifications/', views.NotificationListView.as_view(), name='notification_list'),
    path('roles/', views.UserRolesView.as_view(), name='user_roles'),
    path('settings/', views.SystemSettingsView.as_view(), name='system_settings'),
    path('api/attendance/', views.attendance_api, name='attendance_api'),
    path('api/enrollment/next/', views.enrollment_next_api, name='enrollment_next_api'),
    path('api/enrollment/<int:request_id>/complete/', views.enrollment_complete_api, name='enrollment_complete_api'),
    path('api/enrollment/<int:request_id>/fail/', views.enrollment_fail_api, name='enrollment_fail_api'),
]
