# Generated by Django 6.0.7 on 2026-07-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.team'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.employeeschedule'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='attendance.biometricdevice'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='enrollment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='attendance.enrollmentrequest'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='enrollment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to='attendance.enrollmentrequest'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.officelocation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.officelocation'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='attendance.officelocation'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='remoteworklog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remoteworklog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_work_logs', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_schedules', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='attendance.employee'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'created_at'], name='attendance__device__aa0126_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type', 'created_at'], name='attendance__event_t_c29995_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status', 'created_at'], name='attendance__device__d1982c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['employee', 'created_at'], name='attendance__employe_d2f8e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='attendance__employe_52ea70_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='attendance__status_ddc797_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date', 'department', 'office_location')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization_id'], name='attendance__organiz_8a1734_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'employment_status'], name='attendance__departm_9169a1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['team', 'employment_status'], name='attendance__team_id_446f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager', 'employment_status'], name='attendance__manager_1cf4be_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_type', 'employment_status'], name='attendance__employm_97361e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['employee', 'effective_start', 'effective_end'], name='attendance__employe_ec093e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['department', 'effective_start'], name='attendance__departm_1e9dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['rotation_group'], name='attendance__rotatio_015bce_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
