# Generated by Django 6.0.4 on 2026-07-30 09:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('expected_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('lunch_minutes', models.PositiveIntegerField(default=0)),
                ('missing_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('weekend_minutes', models.PositiveIntegerField(default=0)),
                ('holiday_minutes', models.PositiveIntegerField(default=0)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('on_leave', models.BooleanField(default=False)),
                ('leave_type', models.CharField(blank=True, max_length=20)),
                ('leave_is_paid', models.BooleanField(default=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('recalculation_count', models.PositiveIntegerField(default=0)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Time Summary',
                'verbose_name_plural': 'Daily Time Summaries',
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveIntegerField(db_index=True)),
                ('expected_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('missing_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('weekend_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('night_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('approved_leave_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('unpaid_leave_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('paid_leave_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('paid_leave_days', models.PositiveIntegerField(default=0)),
                ('unpaid_leave_days', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('recalculation_count', models.PositiveIntegerField(default=0)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Monthly Time Summary',
                'verbose_name_plural': 'Monthly Time Summaries',
                'ordering': ['-year', '-month', 'employee__first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance Event', 'verbose_name_plural': 'Attendance Events'},
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='biometric_method',
            field=models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('IRIS', 'Iris Scan'), ('CARD', 'RFID Card'), ('PIN', 'PIN Code'), ('MOBILE', 'Mobile App'), ('MANUAL', 'Manual Entry')], default='FINGERPRINT', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='event_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End'), ('LUNCH_START', 'Lunch Start'), ('LUNCH_END', 'Lunch End'), ('REMOTE_LOGIN', 'Remote Login'), ('REMOTE_LOGOUT', 'Remote Logout'), ('SITE_VISIT', 'Site Visit')], db_index=True, default='CHECK_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='fingerprint_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('PENDING', 'Pending Verification'), ('BYPASSED', 'Bypassed')], default='VERIFIED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'event_type'], name='attendance__employe_60fb19_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_63e069_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['event_type', 'timestamp'], name='attendance__event_t_a56934_idx'),
        ),
        migrations.AddField(
            model_name='dailytimesummary',
            name='attendance_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_summary', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='dailytimesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_time_summaries', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='monthlytimesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_time_summaries', to='attendance.employee'),
        ),
        migrations.AddIndex(
            model_name='dailytimesummary',
            index=models.Index(fields=['date'], name='attendance__date_10e3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimesummary',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_49a99f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytimesummary',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='monthlytimesummary',
            index=models.Index(fields=['year', 'month'], name='attendance__year_03ed92_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytimesummary',
            index=models.Index(fields=['employee', 'year', 'month'], name='attendance__employe_3dea52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytimesummary',
            unique_together={('employee', 'year', 'month')},
        ),
    ]
