# Generated by Django 6.0.7 on 2026-07-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_officelocation_shift_systemsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('serial_port', models.CharField(default='/dev/ttyUSB0', max_length=120)),
                ('baudrate', models.PositiveIntegerField(default=9600)),
                ('mode', models.CharField(choices=[('ATTENDANCE', 'Attendance Mode'), ('ENROLLMENT', 'Fingerprint Enrollment Mode'), ('DELETION', 'Fingerprint Deletion Mode'), ('MAINTENANCE', 'Maintenance Mode'), ('OFFLINE', 'Offline')], default='ATTENDANCE', max_length=24)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy'), ('ERROR', 'Error')], default='OFFLINE', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('template_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='attendance.biometricdevice'),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('ENROLL', 'Enroll'), ('DELETE', 'Delete'), ('VERIFY', 'Verify'), ('DEVICE_STATUS', 'Device Status'), ('RESTART', 'Restart'), ('MAINTENANCE', 'Maintenance'), ('ATTENDANCE_MODE', 'Attendance Mode')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('raw_command', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='attendance.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to='attendance.employee')),
                ('enrollment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to='attendance.enrollmentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENROLL_PROGRESS', 'Enrollment Progress'), ('ENROLL_SUCCESS', 'Enrollment Success'), ('DELETE_SUCCESS', 'Deletion Success'), ('ATTENDANCE_EVENT', 'Attendance Event'), ('DEVICE_STATUS', 'Device Status'), ('COMMAND_ACK', 'Command Acknowledgement'), ('ERROR', 'Error'), ('RAW', 'Raw Message')], db_index=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('fingerprint_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='attendance.devicecommand')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to='attendance.employee')),
                ('enrollment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='attendance.enrollmentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status', 'created_at'], name='attendance__device__d1982c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['employee', 'created_at'], name='attendance__employe_d2f8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'created_at'], name='attendance__device__aa0126_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type', 'created_at'], name='attendance__event_t_c29995_idx'),
        ),
    ]
