# Generated by Django 6.0.7 on 2026-07-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_biometricdevice_enrollmentrequest_progress_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'employee__first_name'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'ordering': ['name'], 'verbose_name': 'Biometric Device', 'verbose_name_plural': 'Biometric Devices'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='devicecommand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device Command', 'verbose_name_plural': 'Device Commands'},
        ),
        migrations.AlterModelOptions(
            name='deviceevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device Event', 'verbose_name_plural': 'Device Events'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ['-effective_start', 'employee__first_name'], 'verbose_name': 'Employee Schedule', 'verbose_name_plural': 'Employee Schedules'},
        ),
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Enrollment Request', 'verbose_name_plural': 'Enrollment Requests'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date', 'name'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year', 'leave_type'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-start_date'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='officelocation',
            options={'ordering': ['name'], 'verbose_name': 'Office Location', 'verbose_name_plural': 'Office Locations'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time', 'name'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['key'], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
    ]
