# Generated by Django 6.0.7 on 2026-07-30 07:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryprofile',
            name='break_duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Break Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='days_per_week',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='expected_daily_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Hours Per Day'),
        ),
    ]
